# Generated by Django 5.1 on 2024-08-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_category_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=9, unique=True)),
                ("password", models.CharField(max_length=9)),
                ("mobile_number", models.CharField(max_length=10)),
            ],
        ),
    ]
